import { test, expect } from '@playwright/test';
import { randomUUID } from 'node:crypto';

test('overview, separate columns, filtering and responsive layout', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'Clarity. From the very first check.' })).toBeVisible();
  await page.screenshot({ path: 'test-results/overview-desktop.png', fullPage: true });
  await page.getByRole('link', { name: /Applications/ }).first().click();
  await expect(page.getByRole('columnheader', { name: 'Discrepancies' })).toBeVisible();
  await expect(page.getByRole('columnheader', { name: 'Watchlist risk' })).toBeVisible();
  await page.getByRole('textbox', { name: 'Search by name or application ID…' }).fill('NoSuchPersonZZZZ');
  await expect(page.getByText('No matching applications')).toBeVisible();
  await page.getByRole('button', { name: 'Clear filters' }).click();
  await page.getByLabel('Filter watchlist risk').selectOption('HIGH');
  await expect(page).toHaveURL(/risk=HIGH/);
  await expect(page.locator('tbody .risk-high').first()).toBeVisible();
  await expect(page.locator('tbody .risk-low, tbody .risk-medium')).toHaveCount(0);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'Clarity. From the very first check.' })).toBeVisible();
  const overflow = await page.evaluate(() => ({ width: window.innerWidth, scroll: document.documentElement.scrollWidth, elements: Array.from(document.querySelectorAll('main > *, .bottom-grid, .recent-panel')).map(el => ({ tag: el.className, width: el.getBoundingClientRect().width, right: el.getBoundingClientRect().right })).filter(el => el.right > window.innerWidth) }));
  expect(overflow.scroll, JSON.stringify(overflow)).toBeLessThanOrEqual(overflow.width);
  await page.screenshot({ path: 'test-results/overview-mobile.png', fullPage: true });
  await page.getByRole('button', { name: 'Open navigation' }).click();
  await page.getByRole('link', { name: 'Watchlist', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Stay a step ahead.' })).toBeVisible();
  expect(errors).toEqual([]);
});

test('onboard, compare, decide, re-screen and dismiss a watchlist match', async ({ page }) => {
  const name = `Test ${randomUUID().replaceAll('-', '')}`;
  await page.goto('/applications/new');
  await expect(page.getByRole('heading', { name: 'Let’s get to know your applicant.' })).toBeVisible();
  await page.screenshot({ path: 'test-results/onboarding-desktop.png', fullPage: true });
  await page.getByLabel('Full name', { exact: true }).fill(name);
  await page.getByLabel('Date of birth', { exact: true }).fill('1994-06-12');
  await page.getByLabel('Residential address').fill('24 Garden Lane, Pune, 411001');
  await page.getByLabel('ID number', { exact: true }).fill('123456789012');
  await page.getByLabel('Occupation').fill('Engineer');
  await page.getByLabel('Annual income').fill('800000');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByLabel('Full name on ID').fill(name);
  await page.getByLabel('Date of birth on ID').fill('1994-06-12');
  await page.getByLabel('Address on ID').fill('25 Garden Lane, Pune, 411001');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Submit & screen' }).click();
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible();
  await expect(page.getByText('1 discrepancy', { exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Low risk', exact: true })).toBeVisible();
  const detailUrl = page.url();
  await page.screenshot({ path: 'test-results/applicant-detail.png', fullPage: true });
  await page.getByRole('button', { name: 'Approve application', exact: true }).click();
  await page.getByLabel('Reviewer name').fill('Browser Test Officer');
  await page.getByLabel('Decision reason').fill('Address change verified with the applicant. No watchlist evidence.');
  await page.getByRole('button', { name: 'Record decision' }).click();
  await expect(page.getByRole('heading', { name: 'Decision recorded' })).toBeVisible();
  await page.goto('/watchlist');
  await page.getByRole('button', { name: 'Add watchlist entry' }).click();
  await page.getByLabel('Full name', { exact: true }).fill(name);
  await page.getByLabel('Country', { exact: true }).fill('India');
  await page.getByLabel('Reason for listing').fill('Synthetic test watchlist record for end-to-end verification');
  await page.getByRole('button', { name: 'Add & re-screen' }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.goto(detailUrl);
  await expect(page.getByRole('heading', { name: 'High risk', exact: true })).toBeVisible();
  await expect(page.getByText('In review', { exact: true })).toBeVisible();
  await expect(page.getByText('1 discrepancy', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Re-screen', exact: true }).click();
  await expect(page.getByRole('status').filter({ hasText: 'Screening complete.' })).toBeVisible();
  await expect(page.locator('.match-card')).toHaveCount(1);
  await page.getByRole('button', { name: 'Dismiss as false positive' }).click();
  await page.getByLabel('Reviewer name').fill('Browser Test Officer');
  await page.getByLabel('Decision reason').fill('Confirmed a different individual after reviewing the ID.');
  await page.getByRole('button', { name: 'Confirm dismissal' }).click();
  await expect(page.getByRole('heading', { name: 'Low risk', exact: true })).toBeVisible();
  await expect(page.getByText('1 discrepancy', { exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Low risk', exact: true })).toBeVisible();
  await page.getByRole('link', { name: 'Activity log', exact: true }).click();
  await page.getByRole('textbox', { name: 'Search applicants, reviewers, or notes…' }).fill(name);
  await expect(page.getByText('Watchlist match dismissed', { exact: true })).toBeVisible();
  await expect(page.getByText('Application approved', { exact: true })).toBeVisible();
});

test('connection errors are actionable and retryable', async ({ page }) => {
  await page.route('**/api/workspace/applications', route => route.abort());
  await page.goto('/');
  await expect(page.getByRole('alert')).toContainText('Unable to reach the workspace');
  await page.unroute('**/api/workspace/applications');
  await page.getByRole('button', { name: 'Try again' }).click();
  await expect(page.getByRole('heading', { name: 'Clarity. From the very first check.' })).toBeVisible();
});
