import { useEffect, useRef, type ReactNode } from 'react';
import { Link } from 'react-router-dom';
import { ArrowUpRight, Check, ChevronLeft, ChevronRight, CircleAlert, Inbox, LoaderCircle, Search, X } from 'lucide-react';
import type { Applicant, Audit, Risk, Status } from './types';
export const labels: Record<string, string> = { PENDING: 'Pending', IN_REVIEW: 'In review', APPROVED: 'Approved', REJECTED: 'Rejected', LOW: 'Low', MEDIUM: 'Medium', HIGH: 'High', MATCH: 'Match', PARTIAL_MATCH: 'Partial match', MISMATCH: 'Mismatch', MISSING: 'Missing', FORMAT_INVALID: 'Invalid format', NOT_VERIFIED: 'Manual check', FALSE_POSITIVE: 'Dismissed', DISMISSED: 'Dismissed', REVIEWED: 'Reviewed', PENDING_REVIEW: 'Needs review', name: 'Full name', dob: 'Date of birth', address: 'Address', id_number: 'ID number format', id_record: 'ID record' };
export const initials = (name: string) => name.split(' ').filter(Boolean).slice(0, 2).map(n => n[0]).join('').toUpperCase();
export function dateLabel(value: string, time = false) { const d = new Date(value.includes('T') && !/[Z+]\d*$/.test(value) ? value + 'Z' : value); return d.toLocaleDateString('en-GB', { day: 'numeric', month: 'short', ...(time ? { hour: '2-digit', minute: '2-digit' } : { year: 'numeric' }) }); }
export function RiskBadge({ risk }: { risk: Risk }) { return <span className={`badge risk-${risk.toLowerCase()}`}><span className="dot" />{labels[risk]} risk</span>; }
export function StatusBadge({ status }: { status: Status }) { return <span className={`badge status-${status.toLowerCase()}`}>{status === 'APPROVED' && <Check size={12}/>}<span>{labels[status]}</span></span>; }
export function Discrepancies({ applicant }: { applicant: Applicant }) { return <div className="findings-cell">{applicant.discrepancy_count ? <span className="finding-warning"><CircleAlert size={14}/>{applicant.discrepancy_count} {applicant.discrepancy_count === 1 ? 'finding' : 'findings'}</span> : <span className="finding-clear"><Check size={14}/>No discrepancies</span>}{applicant.unverified_count > 0 && <small>Manual ID check needed</small>}</div>; }
export function PageHeading({ eyebrow, title, description, action }: { eyebrow?: string; title: string; description: string; action?: ReactNode }) { return <div className="page-heading"><div>{eyebrow && <span className="eyebrow">{eyebrow}</span>}<h1>{title}</h1><p>{description}</p></div>{action}</div>; }
export function Empty({ title = 'Nothing here yet', text, action }: { title?: string; text: string; action?: ReactNode }) { return <div className="empty"><span className="empty-icon"><Inbox size={25}/></span><h3>{title}</h3><p>{text}</p>{action}</div>; }
export function Loading() { return <div className="loading" role="status"><LoaderCircle className="spin" size={22}/>Loading your workspace…</div>; }
export function ErrorNotice({ message, retry }: { message: string; retry?: () => void }) { return <div className="error-notice" role="alert"><CircleAlert size={18}/><span>{message}</span>{retry && <button className="text-button" onClick={retry}>Try again</button>}</div>; }
export function SearchBox({ value, onChange, placeholder = 'Search by name or application ID…' }: { value: string; onChange: (value: string) => void; placeholder?: string }) { return <label className="search-box"><Search size={17}/><input aria-label={placeholder} value={value} onChange={e => onChange(e.target.value)} placeholder={placeholder}/>{value && <button type="button" aria-label="Clear search" onClick={() => onChange('')}><X size={15}/></button>}</label>; }
export function ApplicantTable({ rows }: { rows: Applicant[] }) { return <div className="table-scroll"><table className="data-table"><thead><tr><th>Applicant</th><th>Country</th><th>Discrepancies</th><th>Watchlist risk</th><th>Status</th><th><span className="sr-only">View application</span></th></tr></thead><tbody>{rows.map(a => <tr key={a.application_id}><td><Link className="person" to={`/applications/${a.application_id}`}><span className={`avatar tone-${a.full_name.length % 4}`}>{initials(a.full_name)}</span><span><strong>{a.full_name}</strong><small>{a.application_id.length > 15 ? a.application_id.slice(0, 8).toUpperCase() : a.application_id}</small></span></Link></td><td className="country-cell">{a.country}</td><td><Discrepancies applicant={a}/></td><td><RiskBadge risk={a.risk_level}/></td><td><StatusBadge status={a.status}/></td><td><Link className="row-link" to={`/applications/${a.application_id}`} aria-label={`Review ${a.full_name}`}><ArrowUpRight size={18}/></Link></td></tr>)}</tbody></table></div>; }
export function Pagination({ page, count, size = 8, onChange }: { page: number; count: number; size?: number; onChange: (page: number) => void }) { return <div className="pagination"><span>{count ? `${page * size + 1}–${Math.min((page + 1) * size, count)} of ${count}` : '0 results'}</span><div><button className="icon-button" aria-label="Previous page" disabled={page === 0} onClick={() => onChange(page - 1)}><ChevronLeft size={17}/></button><span>Page {page + 1} of {Math.max(1, Math.ceil(count / size))}</span><button className="icon-button" aria-label="Next page" disabled={(page + 1) * size >= count} onClick={() => onChange(page + 1)}><ChevronRight size={17}/></button></div></div>; }
export function Modal({ title, children, onClose }: { title: string; children: ReactNode; onClose: () => void }) {
  const ref = useRef<HTMLDialogElement>(null);
  useEffect(() => { const dialog = ref.current; dialog?.showModal(); return () => dialog?.close(); }, []);
  return <dialog ref={ref} className="modal" aria-labelledby="dialog-title" onCancel={e => { e.preventDefault(); onClose(); }} onClick={e => { if (e.target === e.currentTarget) onClose(); }}><div className="modal-inner"><div className="modal-header"><h2 id="dialog-title">{title}</h2><button className="icon-button" aria-label="Close dialog" onClick={onClose}><X size={19}/></button></div>{children}</div></dialog>;
}
export function Timeline({ audits, names = {} }: { audits: Audit[]; names?: Record<string, string> }) { return <div className="timeline">{audits.map(a => <div className="timeline-item" key={a.audit_id}><span className={`timeline-dot ${a.action.includes('APPROVED') ? 'green' : ''}`}><Check size={11}/></span><div><div className="timeline-title"><strong>{a.action === 'SCREENING_COMPLETED' ? 'Screening completed' : a.action === 'APPLICATION_CREATED' ? 'Application submitted' : a.action === 'WATCHLIST_MATCH_DISMISSED' ? 'Watchlist match dismissed' : a.action.includes('REJECT') ? 'Application rejected' : a.action.includes('APPROV') ? 'Application approved' : a.action.replaceAll('_', ' ').toLowerCase()}</strong><time>{dateLabel(a.timestamp, true)}</time></div>{names[a.application_id] && <Link className="activity-applicant" to={`/applications/${a.application_id}`}>{names[a.application_id]}</Link>}<p>{a.reason}</p><small>{a.performed_by}{a.old_status && a.new_status && a.old_status !== a.new_status ? ` · ${labels[a.old_status] || a.old_status} → ${labels[a.new_status] || a.new_status}` : ''}</small></div></div>)}</div>; }
