import { useEffect, useState, type FormEvent } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, Check, CircleAlert, FileCheck2, RefreshCw, ShieldCheck, ShieldAlert, X, LoaderCircle, Info } from 'lucide-react';
import { useWorkspace } from './store';
import { api } from './api';
import type { Applicant, Match } from './types';
import { dateLabel, Empty, ErrorNotice, initials, labels, Loading, Modal, RiskBadge, StatusBadge, Timeline } from './components';

export function ApplicantDetail() {
  const { id } = useParams();
  const { audits, refresh, notify } = useWorkspace();
  const [applicant, setApplicant] = useState<Applicant | null>(null), [error, setError] = useState(''), [busy, setBusy] = useState(false), [modalError, setModalError] = useState('');
  const [decision, setDecision] = useState<'APPROVED' | 'REJECTED' | null>(null), [dismiss, setDismiss] = useState<Match | null>(null);
  useEffect(() => { let active = true; setApplicant(null); setError(''); api<Applicant>(`/workspace/applications/${id}`).then(a => { if (active) setApplicant(a); }).catch(e => { if (active) setError(e.message); }); return () => { active = false; }; }, [id]);
  async function rescreen() { setBusy(true); setError(''); try { setApplicant(await api<Applicant>(`/workspace/applications/${id}/screen`, {})); await refresh(); notify('Screening complete. Findings are up to date.'); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setBusy(true); setModalError(''); const data = Object.fromEntries(new FormData(e.currentTarget)); try { const path = dismiss ? `/workspace/matches/${dismiss.screening_id}/dismiss` : `/workspace/applications/${id}/decision`; setApplicant(await api<Applicant>(path, { ...data, ...(decision ? { decision } : {}) })); await refresh(); setDecision(null); setDismiss(null); notify(dismiss ? 'Match dismissed. Watchlist risk has been recalculated.' : 'Decision recorded in the audit trail.'); } catch (e) { setModalError((e as Error).message); } finally { setBusy(false); } }
  if (!applicant) return error ? <ErrorNotice message={error}/> : <Loading/>;
  const a = applicant;
  const final = ['APPROVED', 'REJECTED'].includes(a.status);
  const activeMatches = (a.matches || []).filter(m => !['FALSE_POSITIVE', 'DISMISSED'].includes(m.review_status));
  const appValues: Record<string, string> = { name: a.full_name, dob: a.dob, address: a.address || 'Not provided', id_number: a.id_number, id_record: 'Applicant details provided' };
  const idValues: Record<string, string> = { name: a.identity?.name_on_id || 'Not provided', dob: a.identity?.dob_on_id || 'Not provided', address: a.identity?.address_on_id || 'Not provided', id_number: `Format rule · ${a.country}`, id_record: 'Not available' };
  return <><Link className="back-link" to="/applications"><ArrowLeft size={16}/>Back to applications</Link><div className="detail-heading"><div className="person"><span className="avatar avatar-large tone-0">{initials(a.full_name)}</span><div><h1>{a.full_name}</h1><p>{a.application_id.length > 15 ? a.application_id.slice(0, 8).toUpperCase() : a.application_id} <span>·</span> {a.country} <span>·</span> Submitted {dateLabel(a.created_at)}</p></div></div><StatusBadge status={a.status}/></div>{error && <ErrorNotice message={error}/>}
    <div className="detail-grid"><div className="detail-main"><section className="panel"><div className="panel-heading"><div><h2><FileCheck2 size={18}/>Identity comparison</h2><p>The application and ID record, side by side.</p></div><span className={`badge ${a.discrepancy_count ? 'risk-medium' : 'neutral-badge'}`}>{a.discrepancy_count} {a.discrepancy_count === 1 ? 'discrepancy' : 'discrepancies'}</span></div><div className="table-scroll"><table className="data-table comparison-table"><thead><tr><th>Field</th><th>Application</th><th>ID record / rule</th><th>Result</th></tr></thead><tbody>{a.checks.map(c => <tr key={c.field}><td><strong>{labels[c.field] || c.field}</strong></td><td>{appValues[c.field]}</td><td>{idValues[c.field]}</td><td><span className={`check-result ${c.status === 'MATCH' ? 'is-match' : c.status === 'NOT_VERIFIED' ? 'is-neutral' : 'is-finding'}`}>{c.status === 'MATCH' ? <Check size={14}/> : <CircleAlert size={14}/>} {labels[c.status] || c.status}</span></td></tr>)}</tbody></table></div>{a.checks.some(c => c.status !== 'MATCH') && <div className="finding-explanations">{a.checks.filter(c => c.status !== 'MATCH').map(c => <div key={c.field}><CircleAlert size={15}/><p><strong>{labels[c.field]}:</strong> {c.reason}</p></div>)}</div>}<div className="panel-footnote"><Info size={14}/>Identity findings do not change the watchlist risk rating.</div></section>
    <section className="panel"><div className="panel-heading"><div><h2><ShieldCheck size={18}/>Watchlist screening <span className="count-pill">{activeMatches.length}</span></h2><p>Potential name matches requiring human review.</p></div><button className="button secondary small" disabled={busy} onClick={() => void rescreen()}><RefreshCw size={14} className={busy ? 'spin' : ''}/>Re-screen</button></div>{!a.matches?.length ? <div className="all-clear"><span><ShieldCheck size={23}/></span><div><h3>No watchlist matches found</h3><p>No name similarities met the screening threshold.</p></div></div> : <div className="match-list">{a.matches.map(m => { const dismissed = ['FALSE_POSITIVE', 'DISMISSED'].includes(m.review_status); return <div className={`match-card ${dismissed ? 'dismissed' : ''}`} key={m.screening_id}><div className="match-card-top"><div><h3>{m.name}</h3><p>{m.country || 'Country not listed'} · {m.watchlist_reason}</p></div><span className="match-score">{m.match_score.toFixed(1)}%<small>name similarity</small></span></div><p className="match-reason">{m.reason}</p><div className="match-card-bottom"><span className={`badge ${dismissed ? 'neutral-badge' : 'risk-medium'}`}>{labels[m.review_status] || m.review_status}</span>{!dismissed && <button className="text-button" disabled={busy} onClick={() => { setDismiss(m); setModalError(''); }}>Dismiss as false positive</button>}{dismissed && <small>Reviewed by {m.reviewed_by}</small>}</div></div>; })}</div>}</section>
    <section className="panel"><div className="panel-heading"><div><h2>Application history</h2><p>Checks and decisions, with a complete record of who and why.</p></div></div>{audits.some(l => l.application_id === id) ? <Timeline audits={audits.filter(l => l.application_id === id)}/> : <Empty text="No activity has been recorded yet."/>}</section></div>
    <aside className="detail-aside"><section className="panel risk-panel"><span className="eyebrow">WATCHLIST RISK</span><div className={`risk-emblem risk-${a.risk_level.toLowerCase()}`}>{a.risk_level === 'LOW' ? <ShieldCheck size={30}/> : <ShieldAlert size={30}/>}</div><h2>{labels[a.risk_level]} risk</h2><p>{a.watchlist_matches ? `${a.watchlist_matches} active watchlist ${a.watchlist_matches === 1 ? 'match' : 'matches'}. Strongest name similarity: ${a.highest_match.toFixed(1)}%.` : 'No active watchlist matches above the screening threshold.'}</p><div className="risk-scale"><span className={a.risk_level === 'LOW' ? 'selected' : ''}/><span className={a.risk_level === 'MEDIUM' ? 'selected' : ''}/><span className={a.risk_level === 'HIGH' ? 'selected' : ''}/></div><div className="risk-scale-labels"><span>Low</span><span>Medium</span><span>High</span></div><details className="risk-policy"><summary>How is risk determined?</summary><p>Low: no active match ≥75%. Medium: a match from 75% to below 90%. High: a match ≥90%. Dismissed false positives are excluded. Name similarity is a review signal, not proof of identity.</p></details></section>
    <section className="panel applicant-info"><h3>Applicant details</h3><dl><div><dt>Occupation</dt><dd>{a.occupation || 'Not provided'}</dd></div><div><dt>Annual income</dt><dd>{a.annual_income?.toLocaleString() ?? 'Not provided'}<small>Local currency</small></dd></div><div><dt>Date of birth</dt><dd>{dateLabel(a.dob)}</dd></div></dl></section>
    <section className="panel decision-panel"><h3>{final ? 'Decision recorded' : 'Make a considered decision'}</h3><p>{final ? 'This decision is saved. New watchlist evidence will reopen the application for review.' : 'Review identity discrepancies and watchlist evidence before making your decision.'}</p>{final ? <StatusBadge status={a.status}/> : <><button className="button primary full-width" disabled={busy} onClick={() => { setDecision('APPROVED'); setModalError(''); }}><Check size={16}/>Approve application</button><button className="button danger-outline full-width" disabled={busy} onClick={() => { setDecision('REJECTED'); setModalError(''); }}><X size={16}/>Reject application</button><small>Your name and decision reason will be recorded.</small></>}</section></aside></div>
    {(decision || dismiss) && <Modal title={dismiss ? 'Dismiss watchlist match' : decision === 'APPROVED' ? 'Approve application' : 'Reject application'} onClose={() => { if (!busy) { setDecision(null); setDismiss(null); } }}><p className="modal-description">{dismiss ? `Explain why the match with ${dismiss.name} is a false positive. It will be excluded from watchlist risk.` : `Record your decision for ${a.full_name}. ${a.discrepancy_count ? `${a.discrepancy_count} identity finding(s) remain on record. ` : ''}${activeMatches.length ? `${activeMatches.length} active watchlist match(es) remain on record.` : ''}`}</p><form onSubmit={submit}>{modalError && <ErrorNotice message={modalError}/>}<label className="field">Reviewer name<input name="reviewed_by" required minLength={2} maxLength={100} placeholder="Your full name" autoFocus/></label><label className="field">Decision reason<textarea name="reason" required minLength={5} maxLength={2000} rows={4} placeholder="Explain the evidence and your decision…"/></label><div className="modal-actions"><button className="button secondary" type="button" disabled={busy} onClick={() => { setDecision(null); setDismiss(null); }}>Cancel</button><button className={`button ${decision === 'REJECTED' ? 'danger' : 'primary'}`} disabled={busy}>{busy ? <><LoaderCircle className="spin" size={16}/>Saving…</> : dismiss ? 'Confirm dismissal' : 'Record decision'}</button></div></form></Modal>}
  </>;
}
