import { useEffect, useState, type FormEvent } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { ArrowLeft, ArrowRight, Check, CheckCheck, FileCheck2, LoaderCircle, ShieldCheck, UserRound } from 'lucide-react';
import { api } from './api';
import { useWorkspace } from './store';
import { PageHeading, ErrorNotice } from './components';
import type { Applicant } from './types';

const countries = ['India', 'United States', 'United Arab Emirates', 'United Kingdom', 'Singapore', 'Germany', 'Brazil', 'China', 'Iran', 'Nigeria', 'Pakistan', 'Russia'];
const emptyForm = { full_name: '', dob: '', address: '', id_number: '', occupation: '', annual_income: '', country: 'India', name_on_id: '', dob_on_id: '', address_on_id: '' };
export function OnboardingPage() {
  const [step, setStep] = useState(0), [form, setForm] = useState(emptyForm), [missing, setMissing] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const { refresh, notify } = useWorkspace();
  const navigate = useNavigate();
  const dirty = Object.entries(form).some(([k, v]) => k !== 'country' && v);
  useEffect(() => { const handler = (e: BeforeUnloadEvent) => { if (dirty && !busy) e.preventDefault(); }; window.addEventListener('beforeunload', handler); return () => window.removeEventListener('beforeunload', handler); }, [dirty, busy]);
  const change = (name: keyof typeof form, value: string) => setForm(f => ({ ...f, [name]: value }));
  const steps = [{ title: 'Applicant details', description: 'The person behind the application', icon: UserRound }, { title: 'Identity record', description: 'Details to compare against', icon: FileCheck2 }, { title: 'Review & submit', description: 'Check the details before screening', icon: CheckCheck }];
  const today = new Date().toLocaleDateString('en-CA');
  async function submit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); setError('');
    if (step < 2) { setStep(step + 1); window.scrollTo({ top: 0, behavior: 'smooth' }); return; }
    setBusy(true);
    try {
      const { name_on_id, dob_on_id, address_on_id, ...applicant } = form;
      const result = await api<Applicant>('/workspace/applications', { ...applicant, annual_income: Number(form.annual_income), identity: missing ? null : { name_on_id, dob_on_id, address_on_id } });
      await refresh(); notify('Application created. Identity checks and watchlist screening are complete.'); navigate(`/applications/${result.application_id}`);
    } catch (e) { setError((e as Error).message); } finally { setBusy(false); }
  }
  function input(name: keyof typeof form, label: string, options: { type?: string; placeholder?: string; wide?: boolean; minLength?: number } = {}) {
    return <label className={`field ${options.wide ? 'wide' : ''}`}>{label}<input name={name} type={options.type || 'text'} value={form[name]} onChange={e => change(name, e.target.value)} required minLength={options.minLength || (options.type ? undefined : 2)} maxLength={name.includes('address') ? 2000 : 255} max={options.type === 'date' ? today : options.type === 'number' ? 1e12 : undefined} min={options.type === 'number' ? 0 : undefined} step={options.type === 'number' ? '0.01' : undefined} placeholder={options.placeholder}/>{name === 'annual_income' && <small>In the applicant’s local currency. Not used to determine risk.</small>}</label>;
  }
  return <><Link className="back-link" to="/applications"><ArrowLeft size={16}/>Back to applications</Link><PageHeading eyebrow="A THOUGHTFUL FIRST STEP" title="Let’s get to know your applicant." description="Capture the details once. We’ll take care of the checks."/>
    <div className="onboarding-layout"><aside className="form-sidebar"><ol className="step-list">{steps.map((s, i) => <li key={s.title} className={`${step === i ? 'current' : ''} ${step > i ? 'complete' : ''}`} aria-current={step === i ? 'step' : undefined}><span className="step-number">{step > i ? <Check size={16}/> : i + 1}</span><div><strong>{s.title}</strong><small>{s.description}</small></div></li>)}</ol><div className="form-help"><ShieldCheck size={23}/><h3>Clear checks. No guesswork.</h3><p>Identity discrepancies and watchlist risk are shown separately, with the evidence behind each finding.</p><div className="form-help-line"/><p>Submitting an application starts the checks. A compliance officer makes the final decision.</p></div></aside>
    <section className="panel form-panel"><div className="form-panel-title"><span className="step-icon">{step === 0 ? <UserRound size={21}/> : step === 1 ? <FileCheck2 size={21}/> : <CheckCheck size={21}/>}</span><div><h2>{steps[step].title}</h2><p>{step === 0 ? 'Enter the information provided by the applicant.' : step === 1 ? 'Enter the information exactly as it appears on the ID record.' : 'Make sure both sources are entered accurately.'}</p></div><span className="step-caption">Step {step + 1} of 3</span></div><form onSubmit={submit}>
    {error && <ErrorNotice message={error}/>}
    {step === 0 && <div className="form-section"><span className="section-caption">PERSONAL INFORMATION</span><div className="form-grid">{input('full_name', 'Full name', { placeholder: 'e.g. Aanya Sharma', wide: true })}{input('dob', 'Date of birth', { type: 'date' })}<label className="field">Country<select name="country" value={form.country} onChange={e => change('country', e.target.value)}>{countries.map(c => <option key={c}>{c}</option>)}</select></label>{input('address', 'Residential address', { placeholder: 'House number, street, city, and postal code', wide: true, minLength: 3 })}{input('id_number', 'ID number', { placeholder: form.country === 'India' ? '12-digit Aadhaar number' : 'Applicant’s identification number', wide: true, minLength: 1 })}</div><span className="section-caption employment-caption">EMPLOYMENT DETAILS</span><div className="form-grid">{input('occupation', 'Occupation', { placeholder: 'e.g. Software engineer' })}{input('annual_income', 'Annual income', { type: 'number', placeholder: 'e.g. 800000' })}</div></div>}
    {step === 1 && <div className="form-section"><div className="identity-notice"><FileCheck2 size={19}/><p>Use the independent ID record as your source. Differences from the application will be flagged for review.</p></div><label className="checkbox-label"><input type="checkbox" checked={missing} onChange={e => setMissing(e.target.checked)}/><span>ID record is not available<small>The missing record will be flagged as a discrepancy.</small></span></label>{!missing && <div className="form-grid">{input('name_on_id', 'Full name on ID', { placeholder: 'Name exactly as shown on the record', wide: true })}{input('dob_on_id', 'Date of birth on ID', { type: 'date', wide: true })}{input('address_on_id', 'Address on ID', { placeholder: 'Complete address on the record', wide: true, minLength: 3 })}</div>}</div>}
    {step === 2 && <div className="form-section"><div className="review-section-title"><h3>Applicant information</h3><button type="button" className="text-button" onClick={() => setStep(0)}>Edit details</button></div><dl className="review-grid">{[['Full name', form.full_name], ['Date of birth', form.dob], ['Country', form.country], ['ID number', form.id_number], ['Address', form.address], ['Occupation', form.occupation], ['Annual income', Number(form.annual_income).toLocaleString() + ' · local currency']].map(([k, v]) => <div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><div className="review-section-title"><h3>Identity record</h3><button type="button" className="text-button" onClick={() => setStep(1)}>Edit record</button></div>{missing ? <div className="identity-notice">No ID record provided. This application will require identity review.</div> : <dl className="review-grid">{[['Name on ID', form.name_on_id], ['Date of birth on ID', form.dob_on_id], ['Address on ID', form.address_on_id]].map(([k, v]) => <div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>}<div className="submit-note"><ShieldCheck size={18}/><p>We’ll compare the identity data and screen the applicant against the watchlist. This will not automatically approve or reject the application.</p></div></div>}
    <div className="form-actions">{step > 0 ? <button className="button secondary" type="button" disabled={busy} onClick={() => setStep(step - 1)}><ArrowLeft size={16}/>Back</button> : <Link className="button secondary" to="/applications">Cancel</Link>}<span className="required-note">All visible fields are required</span><button className="button primary" disabled={busy}>{busy ? <><LoaderCircle className="spin" size={16}/>Running checks…</> : step === 2 ? <>Submit & screen<ShieldCheck size={16}/></> : <>Continue<ArrowRight size={16}/></>}</button></div></form></section></div>
  </>;
}
