import { useState, type FormEvent } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { ArrowRight, ArrowUpRight, Plus, UsersRound, Clock3, ShieldAlert, CircleCheck, ShieldCheck, ListFilter, ScanLine, LoaderCircle } from 'lucide-react';
import { useWorkspace } from './store';
import { api } from './api';
import { ApplicantTable, Empty, PageHeading, SearchBox, Pagination, Modal, ErrorNotice, Timeline, initials, dateLabel } from './components';
import type { Applicant } from './types';

export function Overview() {
  const { applicants, watchlist, audits } = useWorkspace();
  const pending = applicants.filter(a => ['PENDING', 'IN_REVIEW'].includes(a.status));
  const high = applicants.filter(a => a.risk_level === 'HIGH');
  const approved = applicants.filter(a => a.status === 'APPROVED');
  const riskOrder = { HIGH: 0, MEDIUM: 1, LOW: 2 };
  const queue = [...pending].sort((a, b) => riskOrder[a.risk_level] - riskOrder[b.risk_level] || b.discrepancy_count - a.discrepancy_count).slice(0, 6);
  const stats = [{ label: 'Total applications', value: applicants.length, hint: 'Across your workspace', icon: UsersRound, link: '/applications', tone: 'neutral' }, { label: 'Awaiting decision', value: pending.length, hint: 'Ready for your review', icon: Clock3, link: '/applications?status=OPEN', tone: 'amber' }, { label: 'High watchlist risk', value: high.length, hint: 'Strong name matches', icon: ShieldAlert, link: '/applications?risk=HIGH', tone: 'red' }, { label: 'Approved', value: approved.length, hint: 'Onboarding complete', icon: CircleCheck, link: '/applications?status=APPROVED', tone: 'green' }];
  const names = Object.fromEntries(applicants.map(a => [a.application_id, a.full_name]));
  const discrepancyFields = [{ key: 'name', label: 'Name differences' }, { key: 'dob', label: 'Date of birth' }, { key: 'address', label: 'Address differences' }, { key: 'id_record', label: 'Missing ID records' }].map(item => ({ ...item, count: applicants.filter(a => a.checks.some(c => c.field === item.key && c.status !== 'MATCH')).length }));
  return <>
    <PageHeading eyebrow="YOUR REVIEW DESK" title="Clarity. From the very first check." description="A focused view of your applicants, findings, and decisions." action={<Link className="button primary" to="/applications/new"><Plus size={17}/>New application</Link>}/>
    <div className="stats-grid">{stats.map(s => <Link className="stat-card" key={s.label} to={s.link}><div className="stat-top"><span>{s.label}</span><s.icon size={17} className={`ink-${s.tone}`}/></div><strong>{s.value.toString().padStart(2, '0')}</strong><div className="stat-bottom"><span>{s.hint}</span><ArrowUpRight size={15}/></div></Link>)}</div>
    <div className="overview-grid"><section className="panel queue-panel"><div className="panel-heading"><div><h2>Review queue <span className="count-pill">{pending.length}</span></h2><p>Highest watchlist risk first, followed by identity findings.</p></div><Link className="text-link" to="/applications?status=OPEN">View all <ArrowRight size={15}/></Link></div>{queue.length ? <ApplicantTable rows={queue}/> : <Empty title="You’re all caught up" text="New applications that need a decision will appear here."/>}<div className="panel-footnote"><ShieldCheck size={14}/>Discrepancies and watchlist risk are assessed separately.</div></section>
    <aside className="panel summary-panel"><div className="panel-heading"><div><span className="eyebrow">IDENTITY VERIFICATION</span><h2>A closer look at the details</h2></div><ScanLine size={20}/></div><div className="finding-summary"><strong>{applicants.filter(a => a.discrepancy_count > 0).length}<span> / {applicants.length}</span></strong><p>applications with discrepancies</p></div><div className="finding-bars">{discrepancyFields.map(f => <div className="finding-bar" key={f.key}><div><span>{f.label}</span><strong>{f.count}</strong></div><div className="bar-track"><span style={{ width: `${applicants.length ? f.count / applicants.length * 100 : 0}%` }}/></div></div>)}</div><Link className="button secondary full-width" to="/applications?findings=yes">Explore findings <ArrowRight size={15}/></Link></aside></div>
    <div className="bottom-grid"><section className="panel recent-panel"><div className="panel-heading"><div><h2>Recent activity</h2><p>A record of the work behind every decision.</p></div><Link className="text-link" to="/activity">View log <ArrowRight size={15}/></Link></div>{audits.length ? <Timeline audits={audits.slice(0, 3)} names={names}/> : <Empty title="Your audit trail starts here" text="Application checks and officer decisions will be recorded automatically."/>}</section><section className="watchlist-note"><span className="shield-tile"><ShieldCheck size={26}/></span><span className="eyebrow">CONTINUOUS SCREENING</span><h2>A new name.<br/>A fresh check.</h2><p>Every watchlist addition rechecks your existing applicants, so new matches don’t go unnoticed.</p><div className="watchlist-note-footer"><span><strong>{watchlist.length}</strong> watchlist entries</span><Link className="icon-button" aria-label="Manage watchlist" to="/watchlist"><ArrowUpRight size={20}/></Link></div></section></div>
  </>;
}

export function Applications() {
  const { applicants } = useWorkspace();
  const [params, setParams] = useSearchParams();
  const [search, setSearch] = useState('');
  const [page, setPage] = useState(0);
  const status = params.get('status') || 'ALL', risk = params.get('risk') || 'ALL', findings = params.get('findings') || 'ALL';
  function filter(key: string, value: string) { const next = new URLSearchParams(params); value === 'ALL' ? next.delete(key) : next.set(key, value); setParams(next); setPage(0); }
  const filtered = applicants.filter(a => (status === 'ALL' || (status === 'OPEN' ? ['PENDING', 'IN_REVIEW'].includes(a.status) : a.status === status)) && (risk === 'ALL' || a.risk_level === risk) && (findings === 'ALL' || (findings === 'yes' ? a.discrepancy_count > 0 : a.discrepancy_count === 0)) && `${a.full_name} ${a.application_id} ${a.country}`.toLowerCase().includes(search.toLowerCase()));
  const tabs = [{ key: 'ALL', label: 'All applications' }, { key: 'OPEN', label: 'Awaiting decision' }, { key: 'APPROVED', label: 'Approved' }, { key: 'REJECTED', label: 'Rejected' }];
  const count = (key: string) => applicants.filter(a => key === 'ALL' || (key === 'OPEN' ? ['PENDING', 'IN_REVIEW'].includes(a.status) : a.status === key)).length;
  const safePage = Math.min(page, Math.max(0, Math.ceil(filtered.length / 8) - 1));
  return <><PageHeading eyebrow="CUSTOMER ONBOARDING" title="Every applicant. One clear picture." description="Compare identity findings, assess watchlist risk, and make an informed decision." action={<Link className="button primary" to="/applications/new"><Plus size={17}/>New application</Link>}/><section className="panel"><div className="tabs" role="tablist" aria-label="Application status">{tabs.map(t => <button key={t.key} role="tab" aria-selected={status === t.key} className={status === t.key ? 'selected' : ''} onClick={() => filter('status', t.key)}>{t.label}<span>{count(t.key)}</span></button>)}</div><div className="table-toolbar"><SearchBox value={search} onChange={v => { setSearch(v); setPage(0); }}/><div className="filters"><ListFilter size={16}/><select aria-label="Filter watchlist risk" value={risk} onChange={e => filter('risk', e.target.value)}><option value="ALL">All risk levels</option><option value="LOW">Low risk</option><option value="MEDIUM">Medium risk</option><option value="HIGH">High risk</option></select><select aria-label="Filter discrepancies" value={findings} onChange={e => filter('findings', e.target.value)}><option value="ALL">All discrepancies</option><option value="yes">With findings</option><option value="no">No discrepancies</option></select></div></div>{filtered.length ? <ApplicantTable rows={filtered.slice(safePage * 8, safePage * 8 + 8)}/> : <Empty title={applicants.length ? 'No matching applications' : 'Welcome to your applicant workspace'} text={applicants.length ? 'Try a different search or adjust your filters.' : 'Create an application to start checking identity details and watchlist risk.'} action={applicants.length ? <button className="button secondary" onClick={() => { setParams({}); setSearch(''); }}>Clear filters</button> : <Link className="button primary" to="/applications/new">New application</Link>}/>}<Pagination page={safePage} count={filtered.length} onChange={setPage}/></section><div className="quiet-note"><ShieldCheck size={15}/><span><strong>Two checks. Separate signals.</strong> Discrepancies flag differences in identity data. Risk reflects watchlist matches only.</span></div></>;
}

export function Watchlist() {
  const { watchlist, refresh, notify } = useWorkspace();
  const [search, setSearch] = useState(''), [page, setPage] = useState(0), [open, setOpen] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const rows = watchlist.filter(w => `${w.name} ${w.country} ${w.reason}`.toLowerCase().includes(search.toLowerCase()));
  const safePage = Math.min(page, Math.max(0, Math.ceil(rows.length / 8) - 1));
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const form = new FormData(e.currentTarget); setBusy(true); setError(''); try { const result = await api<{ alerts_generated: number }>('/workspace/watchlist', Object.fromEntries(form)); await refresh(); setOpen(false); notify(`Watchlist updated. ${result.alerts_generated} new ${result.alerts_generated === 1 ? 'match' : 'matches'} found.`); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <><PageHeading eyebrow="ONGOING DUE DILIGENCE" title="Stay a step ahead." description="Manage the names that matter. New entries automatically re-screen all applicants." action={<button className="button primary" onClick={() => { setOpen(true); setError(''); }}><Plus size={17}/>Add watchlist entry</button>}/><div className="screening-banner"><span className="shield-tile"><ShieldCheck size={23}/></span><div><h3>Continuous screening is part of the workflow</h3><p>New matches reopen the application for review. Previous decisions remain in the audit trail.</p></div><span className="badge risk-low"><span className="dot"/>{watchlist.length} entries</span></div><section className="panel"><div className="table-toolbar"><SearchBox value={search} onChange={v => { setSearch(v); setPage(0); }} placeholder="Search names, countries, or reasons…"/><span className="muted">{rows.length} entries</span></div>{rows.length ? <div className="table-scroll"><table className="data-table watchlist-table"><thead><tr><th>Name</th><th>Country</th><th>Reason for listing</th><th>Added</th></tr></thead><tbody>{rows.slice(safePage * 8, safePage * 8 + 8).map(w => <tr key={w.watchlist_id}><td><span className="person"><span className="avatar tone-2">{initials(w.name)}</span><strong>{w.name}</strong></span></td><td>{w.country || 'Not specified'}</td><td>{w.reason}</td><td className="muted nowrap">{dateLabel(w.created_at)}</td></tr>)}</tbody></table></div> : <Empty title="No watchlist entries found" text="Add an entry or try a different search."/>}<Pagination page={safePage} count={rows.length} onChange={setPage}/></section>{open && <Modal title="Add watchlist entry" onClose={() => !busy && setOpen(false)}><p className="modal-description">All applicants will be checked against this name as soon as you add it.</p><form onSubmit={submit}>{error && <ErrorNotice message={error}/>}<label className="field">Full name<input name="name" required minLength={2} maxLength={255} placeholder="Name as listed" autoFocus/></label><label className="field">Country<input name="country" required minLength={2} maxLength={100} placeholder="Country associated with the record"/></label><label className="field">Reason for listing<textarea name="reason" required minLength={5} maxLength={2000} rows={3} placeholder="e.g. Sanctions listing or politically exposed person"/></label><div className="modal-actions"><button type="button" className="button secondary" disabled={busy} onClick={() => setOpen(false)}>Cancel</button><button className="button primary" disabled={busy}>{busy ? <><LoaderCircle className="spin" size={16}/>Screening applicants…</> : <>Add & re-screen<ArrowRight size={16}/></>}</button></div></form></Modal>}</>;
}

export function Activity() {
  const { applicants, audits } = useWorkspace();
  const [search, setSearch] = useState(''), [kind, setKind] = useState('ALL'), [page, setPage] = useState(0);
  const names = Object.fromEntries(applicants.map(a => [a.application_id, a.full_name]));
  const rows = audits.filter(a => (kind === 'ALL' || (kind === 'DECISIONS' ? a.action.includes('APPROV') || a.action.includes('REJECT') || a.action.includes('DISMISS') : a.action.includes('SCREEN'))) && `${names[a.application_id] || ''} ${a.application_id} ${a.performed_by} ${a.reason}`.toLowerCase().includes(search.toLowerCase()));
  const safePage = Math.min(page, Math.max(0, Math.ceil(rows.length / 8) - 1));
  return <><PageHeading eyebrow="THE COMPLETE RECORD" title="Every decision has a story." description="Follow the checks, findings, and people behind each application."/><section className="panel activity-panel"><div className="table-toolbar"><SearchBox value={search} onChange={v => { setSearch(v); setPage(0); }} placeholder="Search applicants, reviewers, or notes…"/><select aria-label="Filter activity" value={kind} onChange={e => { setKind(e.target.value); setPage(0); }}><option value="ALL">All activity</option><option value="DECISIONS">Officer decisions</option><option value="SCREENING">Screening events</option></select></div>{rows.length ? <Timeline audits={rows.slice(safePage * 8, safePage * 8 + 8)} names={names}/> : <Empty title="No activity found" text="Checks and decisions will appear here as you work."/>}<Pagination page={safePage} count={rows.length} onChange={setPage}/></section></>;
}
